spring.application.name=eureka-server


# Port where Eureka runs
server.port=8761


# These 2 lines tell Eureka "don't register yourself"
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false